# Generated by Django 6.0.2 on 2026-02-05 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique crop name (must match ML model label)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload crop image (takes priority over URL)",
                        null=True,
                        upload_to="crops/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="External image URL (used if no file uploaded)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "expected_yield",
                    models.CharField(
                        blank=True,
                        help_text="Expected yield per hectare (e.g., '2-3 tons/hectare')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="Growing season (e.g., 'Kharif', 'Rabi', 'Zaid')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the crop", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Crop",
                "verbose_name_plural": "Crops",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nitrogen",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "phosphorus",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "potassium",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("temperature", models.FloatField()),
                (
                    "humidity",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "ph",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ]
                    ),
                ),
                (
                    "rainfall",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "predictions",
                    models.JSONField(
                        help_text="Top 3 crop predictions with confidence scores"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prediction Log",
                "verbose_name_plural": "Prediction Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
