# Generated by Django 6.0 on 2026-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="image_2",
            field=models.ImageField(
                blank=True,
                help_text="Upload crop image 2 (takes priority over URL)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_2_url",
            field=models.URLField(
                blank=True,
                help_text="Image 2 URL (used if no file uploaded)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_3",
            field=models.ImageField(
                blank=True,
                help_text="Upload crop image 3 (takes priority over URL)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_3_url",
            field=models.URLField(
                blank=True,
                help_text="Image 3 URL (used if no file uploaded)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload crop image 1 (takes priority over URL)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Image 1 URL (used if no file uploaded)",
                max_length=500,
                null=True,
            ),
        ),
    ]
