# Generated by Django 5.2.11 on 2026-02-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_sqlite_wal_and_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="predictionlog",
            name="apps_predic_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="predictionlog",
            name="apps_predic_ip_addr_idx",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="image",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="image_2_url",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="image_3",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="image_3_url",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="image_url",
        ),
    ]
