# Generated by Antigravity on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_remove_image_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Primary crop image (uploaded file)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_2",
            field=models.ImageField(
                blank=True,
                help_text="Secondary crop image (uploaded file)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_2_url",
            field=models.URLField(
                blank=True, help_text="Secondary crop image (external URL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_3",
            field=models.ImageField(
                blank=True,
                help_text="Tertiary crop image (uploaded file)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_3_url",
            field=models.URLField(
                blank=True, help_text="Tertiary crop image (external URL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Primary crop image (external URL)", null=True
            ),
        ),
    ]
