# Generated by Django 5.2.11 on 2026-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("language", models.CharField(default="unknown", max_length=10)),
                (
                    "detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("asked_count", models.IntegerField(default=1)),
                ("first_asked", models.DateTimeField(auto_now_add=True)),
                ("last_asked", models.DateTimeField(auto_now=True)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-asked_count"],
            },
        ),
    ]
