"""
Crop Recommendation ML API — V6 Production
==========================================
Soil-driven stacked ensemble architecture with clean training data.

Architecture:
  "soil"      → V6 stacked ensemble (51 crops, Crop_recommendation_v2.csv)
  "extended"  → Calibrated RF (51 crops, legacy fallback)
  "both"      → Confidence-adaptive blend of soil + extended

V3 stacked ensemble DEPRECATED — trained on circular data (crop-averaged
features from real_world_merged_dataset.csv where per-crop std ≈ 0).

Probability calibration: isotonic regression + temperature scaling (T=0.9).
No inv-freq reweighting, no entropy shaving, no dominance penalty.
"""

import hashlib
import json
import time
import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
import logging
import os

# ═══════════════════════════════════════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════════════════════════════════════

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ml_api_v6")

app = FastAPI(title="Crop Recommendation ML API", version="6.0")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# ═══════════════════════════════════════════════════════════════════════════
# FEATURE RANGES — loaded from feature_ranges.json (single source of truth)
# Generated by train_v6_stacked.py from Crop_recommendation_v2.csv.
# ═══════════════════════════════════════════════════════════════════════════

_RANGES_PATH = os.path.join(BASE_DIR, "feature_ranges.json")
with open(_RANGES_PATH, encoding="utf-8") as _f:
    FEATURE_RANGES: dict = json.load(_f)

_ACC = FEATURE_RANGES["acceptance"]
_V6_FEAT = FEATURE_RANGES["v6_soil_model"]["features"]

logger.info(
    "Loaded feature_ranges.json  acceptance=%s",
    {k: [v["min"], v["max"]] for k, v in _ACC.items() if not k.startswith("_")},
)

# V6 training ranges for OOD guard (warn, don't reject)
TRAINING_RANGES = {
    "soil": {k: {"min": v["min"], "max": v["max"]} for k, v in _V6_FEAT.items()},
    "extended": {k: {"min": v["min"], "max": v["max"]} for k, v in _V6_FEAT.items()},
}
TRAINING_RANGES["both"] = TRAINING_RANGES["soil"]


# ═══════════════════════════════════════════════════════════════════════════
# CONFIDENCE GATING
# ═══════════════════════════════════════════════════════════════════════════

MIN_CONFIDENCE_THRESHOLD = 0.60
ENTROPY_WARNING_THRESHOLD = 2.0


# ═══════════════════════════════════════════════════════════════════════════
# MODE MAPPING — backward-compatible aliases
# ═══════════════════════════════════════════════════════════════════════════

MODE_ALIASES = {
    "soil": "soil",
    "extended": "extended",
    "both": "both",
    # V5 backward compatibility
    "original": "soil",
    "synthetic": "extended",
}
VALID_MODES = set(MODE_ALIASES.keys())
CANONICAL_MODES = {"soil", "extended", "both"}


# ═══════════════════════════════════════════════════════════════════════════
# UTILITIES
# ═══════════════════════════════════════════════════════════════════════════

def infer_season(temperature: float) -> int:
    if temperature >= 28:
        return 0   # Kharif
    if temperature <= 22:
        return 1   # Rabi
    return 2       # Zaid


def get_season_name(code: int) -> str:
    return ["Kharif", "Rabi", "Zaid"][code] if 0 <= code <= 2 else "Unknown"


def file_checksum(path: str) -> str:
    """SHA-256 prefix for integrity verification."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()[:16]


def compute_entropy(proba: np.ndarray) -> float:
    p = proba[proba > 0]
    return float(-np.sum(p * np.log(p)))


def validate_distribution(input_dict: dict, mode: str) -> list:
    """
    Check if inputs fall outside training distribution for *mode*.
    Returns a list of warning dicts (empty when in-distribution).
    Does NOT reject — just warns.
    """
    warnings = []
    ranges = TRAINING_RANGES.get(mode, TRAINING_RANGES["soil"])
    for field, bounds in ranges.items():
        if field not in input_dict:
            continue
        val = input_dict[field]
        if val < bounds["min"] or val > bounds["max"]:
            warnings.append({
                "field": field,
                "value": val,
                "training_range": [bounds["min"], bounds["max"]],
            })
    return warnings


def risk_level(confidence_pct: float) -> str:
    if confidence_pct >= 80:
        return "low"
    if confidence_pct >= 50:
        return "medium"
    return "high"


# ═══════════════════════════════════════════════════════════════════════════
# NUTRITION LOOKUP
# ═══════════════════════════════════════════════════════════════════════════

NUTRITION_MAPPING = {
    "pigeonpea": "pigeonpeas",
    "sesamum": "sesame",
    "pearl_millet": "bajra",
    "finger_millet": "ragi",
    "sorghum": "jowar",
}

try:
    nutrients_df = pd.read_csv(os.path.join(BASE_DIR, "Nutrient.csv"))
    logger.info("Nutrition data loaded.")
except Exception as e:
    logger.error("Failed to load Nutrient.csv: %s", e)
    nutrients_df = pd.DataFrame()


def get_nutrition(crop_name: str) -> Optional[dict]:
    try:
        search = NUTRITION_MAPPING.get(crop_name.lower(), crop_name.lower())
        match = nutrients_df[
            nutrients_df["food_name"].str.contains(search, case=False, na=False)
        ]
        if not match.empty:
            row = match.iloc[0]
            return {
                "protein_g": float(row["protein_g_per_kg"]),
                "fat_g": float(row["fat_g_per_kg"]),
                "carbs_g": float(row["carbs_g_per_kg"]),
                "fiber_g": float(row["fiber_g_per_kg"]),
                "iron_mg": float(row["iron_mg_per_kg"]),
                "calcium_mg": float(row["calcium_mg_per_kg"]),
                "energy_kcal": float(row["energy_kcal_per_kg"]),
                "water_g": float(row["water_g_per_kg"]),
            }
    except Exception as e:
        logger.warning("Nutrition lookup failed for %s: %s", crop_name, e)
    return None


# ═══════════════════════════════════════════════════════════════════════════
# MODEL CLASSES — loaded ONCE at startup, immutable
# ═══════════════════════════════════════════════════════════════════════════

class SoilPredictor:
    """
    V6 Stacked Ensemble — 51 crops, 10 features.

    Base learners : BalancedRF(200) + XGBoost(200) + LightGBM(200)
    Meta-learner  : LogisticRegression → Isotonic calibration
    Temperature   : T=0.9 (sole post-hoc calibration)
    Trained on    : Crop_recommendation_v2.csv (real per-sample variability)
    """

    def __init__(self):
        t0 = time.time()
        model_file = os.path.join(BASE_DIR, "stacked_ensemble_v6.joblib")
        encoder_file = os.path.join(BASE_DIR, "label_encoder_v6.joblib")
        config_file = os.path.join(BASE_DIR, "stacked_v6_config.joblib")

        stacked = joblib.load(model_file)
        self.fold_models = stacked["fold_models"]
        self.meta_learner = stacked["meta_learner"]
        self.label_encoder = joblib.load(encoder_file)
        config = joblib.load(config_file)
        self.features = config["feature_names"]
        self.temperature_param = config.get("temperature", 0.9)

        self.crops = list(self.label_encoder.classes_)
        self.crop_count = len(self.crops)
        self.checksum = file_checksum(model_file)

        elapsed = (time.time() - t0) * 1000
        logger.info(
            "V6 Soil model loaded: %d crops, %d features, T=%.2f, checksum=%s (%.0fms)",
            self.crop_count, len(self.features), self.temperature_param,
            self.checksum, elapsed,
        )

    def predict_proba(self, input_dict: dict) -> np.ndarray:
        X = pd.DataFrame([input_dict])[self.features]

        base_preds = []
        for name in ["BalancedRF", "XGBoost", "LightGBM"]:
            fold_probs = np.mean(
                [m.predict_proba(X)[0] for m in self.fold_models[name]], axis=0
            )
            base_preds.append(fold_probs)

        meta_features = np.hstack(base_preds).reshape(1, -1)
        proba = self.meta_learner.predict_proba(meta_features)[0]

        # Temperature scaling — sole statistically-validated post-process
        if self.temperature_param != 1.0:
            log_p = np.log(np.clip(proba, 1e-10, 1.0))
            scaled = log_p / self.temperature_param
            scaled -= scaled.max()
            e = np.exp(scaled)
            proba = e / e.sum()

        return proba


class ExtendedPredictor:
    """Calibrated Random Forest — 51 crops, 10 features (legacy fallback)."""

    def __init__(self):
        t0 = time.time()
        model_file = os.path.join(BASE_DIR, "model_rf.joblib")
        encoder_file = os.path.join(BASE_DIR, "label_encoder.joblib")

        self.model = joblib.load(model_file)
        self.label_encoder = joblib.load(encoder_file)
        self.features = [
            "N", "P", "K", "temperature", "humidity",
            "ph", "rainfall", "season", "soil_type", "irrigation",
        ]

        self.crops = list(self.label_encoder.classes_)
        self.crop_count = len(self.crops)
        self.checksum = file_checksum(model_file)

        elapsed = (time.time() - t0) * 1000
        logger.info(
            "Extended RF model loaded: %d crops, %d features, checksum=%s (%.0fms)",
            self.crop_count, len(self.features), self.checksum, elapsed,
        )

    def predict_proba(self, input_dict: dict) -> np.ndarray:
        X = pd.DataFrame([input_dict])[self.features]
        return self.model.predict_proba(X)[0]


class HybridPredictor:
    """Confidence-adaptive blend of V6 soil + extended RF."""

    V6_WEIGHT = 0.7
    RF_WEIGHT = 0.3
    CONFIDENCE_THRESHOLD = 0.3

    def __init__(self, soil: SoilPredictor, extended: ExtendedPredictor):
        self.soil = soil
        self.extended = extended

        soil_set = set(soil.crops)
        ext_set = set(extended.crops)
        self.unified_crops = sorted(soil_set | ext_set)
        self.crop_count = len(self.unified_crops)
        self.crop_to_idx = {c: i for i, c in enumerate(self.unified_crops)}

        logger.info(
            "Hybrid predictor ready: %d crops (soil=%d, ext=%d, overlap=%d)",
            self.crop_count, len(soil_set), len(ext_set), len(soil_set & ext_set),
        )

    def predict_proba(self, input_dict: dict) -> np.ndarray:
        soil_proba = self.soil.predict_proba(input_dict)
        ext_proba = self.extended.predict_proba(input_dict)

        sc = float(np.max(soil_proba))
        ec = float(np.max(ext_proba))

        # Adaptive weighting: favour whichever model is more confident
        if sc > self.CONFIDENCE_THRESHOLD and ec > self.CONFIDENCE_THRESHOLD:
            sw, ew = self.V6_WEIGHT, self.RF_WEIGHT
        elif sc > self.CONFIDENCE_THRESHOLD:
            sw, ew = 0.85, 0.15
        elif ec > self.CONFIDENCE_THRESHOLD:
            sw, ew = 0.15, 0.85
        else:
            sw, ew = 0.5, 0.5

        unified = np.zeros(self.crop_count)
        for i, crop in enumerate(self.soil.crops):
            if crop in self.crop_to_idx:
                unified[self.crop_to_idx[crop]] += soil_proba[i] * sw
        for i, crop in enumerate(self.extended.crops):
            if crop in self.crop_to_idx:
                unified[self.crop_to_idx[crop]] += ext_proba[i] * ew

        total = unified.sum()
        if total > 0:
            unified /= total
        return unified


# ═══════════════════════════════════════════════════════════════════════════
# LOAD ALL MODELS AT STARTUP
# ═══════════════════════════════════════════════════════════════════════════

_soil: Optional[SoilPredictor] = None
_extended: Optional[ExtendedPredictor] = None
_hybrid: Optional[HybridPredictor] = None

try:
    _soil = SoilPredictor()
except Exception as e:
    logger.error("FAILED to load V6 soil model: %s", e)

try:
    _extended = ExtendedPredictor()
except Exception as e:
    logger.error("FAILED to load extended RF model: %s", e)

if _soil and _extended:
    _hybrid = HybridPredictor(_soil, _extended)
else:
    logger.error("Cannot build hybrid predictor — missing base model(s)")


# ── STARTUP ASSERTIONS ─────────────────────────────────────────────────

def _assert_startup():
    errors = []

    if _soil:
        if _soil.crop_count != 51:
            errors.append(f"V6 soil model has {_soil.crop_count} crops, expected 51")
    else:
        errors.append("V6 soil model not loaded")

    if _extended:
        if _extended.crop_count != 51:
            errors.append(f"Extended RF has {_extended.crop_count} crops, expected 51")
    else:
        errors.append("Extended RF model not loaded")

    if not _hybrid:
        errors.append("Hybrid predictor not available")

    required_sections = ["acceptance", "v6_soil_model"]
    for sec in required_sections:
        if sec not in FEATURE_RANGES:
            errors.append(f"feature_ranges.json missing '{sec}' section")

    core_features = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]
    for feat in core_features:
        if feat not in _ACC:
            errors.append(f"Acceptance ranges missing feature '{feat}'")
        elif _ACC[feat]["min"] >= _ACC[feat]["max"]:
            errors.append(f"Invalid acceptance range for {feat}: {_ACC[feat]}")

    for e in errors:
        logger.error("STARTUP ASSERTION FAILED: %s", e)
    if not errors:
        logger.info("All startup assertions passed.")

_assert_startup()


# ═══════════════════════════════════════════════════════════════════════════
# API MODELS
# ═══════════════════════════════════════════════════════════════════════════

class PredictionInput(BaseModel):
    """Pydantic input gate — limits sourced from feature_ranges.json acceptance."""
    N: float = Field(..., ge=_ACC["N"]["min"], le=_ACC["N"]["max"],
                     description="Nitrogen (kg/ha)")
    P: float = Field(..., ge=_ACC["P"]["min"], le=_ACC["P"]["max"],
                     description="Phosphorus (kg/ha)")
    K: float = Field(..., ge=_ACC["K"]["min"], le=_ACC["K"]["max"],
                     description="Potassium (kg/ha)")
    temperature: float = Field(..., ge=_ACC["temperature"]["min"],
                               le=_ACC["temperature"]["max"],
                               description="Temperature (°C)")
    humidity: float = Field(..., ge=_ACC["humidity"]["min"],
                            le=_ACC["humidity"]["max"],
                            description="Humidity (%)")
    ph: float = Field(..., ge=_ACC["ph"]["min"], le=_ACC["ph"]["max"],
                      description="Soil pH")
    rainfall: float = Field(..., ge=_ACC["rainfall"]["min"],
                            le=_ACC["rainfall"]["max"],
                            description="Rainfall (mm)")
    moisture: Optional[float] = Field(
        43.5, ge=_ACC["moisture"]["min"], le=_ACC["moisture"]["max"],
        description="Soil moisture (%) — accepted for API compat, not used by V6",
    )
    season: Optional[int] = Field(
        None, ge=_ACC["season"]["min"], le=_ACC["season"]["max"],
        description="0=Kharif, 1=Rabi, 2=Zaid (auto-inferred from temperature if omitted)",
    )
    soil_type: Optional[int] = Field(
        1, ge=_ACC["soil_type"]["min"], le=_ACC["soil_type"]["max"],
        description="Soil type (0-4)",
    )
    irrigation: Optional[int] = Field(
        0, ge=_ACC["irrigation"]["min"], le=_ACC["irrigation"]["max"],
        description="0=rainfed, 1=irrigated",
    )
    mode: Optional[str] = Field(
        "soil",
        description="soil | extended | both  (aliases: original→soil, synthetic→extended)",
    )
    top_n: Optional[int] = Field(3, ge=1, le=10, description="Top N predictions")


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=422,
        content={"detail": exc.errors(), "message": "Invalid input"},
    )


# ═══════════════════════════════════════════════════════════════════════════
# PREDICT ENDPOINT
# ═══════════════════════════════════════════════════════════════════════════

@app.post("/predict")
async def predict(data: PredictionInput):
    start = time.time()
    raw_mode = (data.mode or "soil").strip().lower()

    if raw_mode not in VALID_MODES:
        raise HTTPException(400, f"Invalid mode '{raw_mode}'. Use: {sorted(CANONICAL_MODES)}")

    mode = MODE_ALIASES[raw_mode]
    deprecated_mode = raw_mode != mode  # True if user sent "original"/"synthetic"

    # 1. Season
    season = data.season if data.season is not None else infer_season(data.temperature)

    # 2. Unified feature dict — all V6 models use same uppercase keys
    input_dict = {
        "N": data.N, "P": data.P, "K": data.K,
        "temperature": data.temperature, "humidity": data.humidity,
        "ph": data.ph, "rainfall": data.rainfall,
        "season": season,
        "soil_type": data.soil_type,
        "irrigation": data.irrigation,
    }

    # Canonical features for OOD check (only core numeric features)
    canonical = {
        "N": data.N, "P": data.P, "K": data.K,
        "temperature": data.temperature, "humidity": data.humidity,
        "ph": data.ph, "rainfall": data.rainfall,
    }

    # 3. Distribution validation — warn, don't reject
    ood_warnings = validate_distribution(canonical, mode)
    if ood_warnings:
        logger.warning("OOD inputs for mode=%s: %s", mode, ood_warnings)

    # 4. Inference
    try:
        if mode == "soil":
            if not _soil:
                raise HTTPException(503, "V6 soil model unavailable")
            proba = _soil.predict_proba(input_dict)
            crops_list = _soil.crops
            mtype = "stacked-ensemble-v6"
            mchk = _soil.checksum
            mcrop = _soil.crop_count
            nfeat = len(_soil.features)

        elif mode == "extended":
            if not _extended:
                raise HTTPException(503, "Extended RF model unavailable")
            proba = _extended.predict_proba(input_dict)
            crops_list = _extended.crops
            mtype = "calibrated-rf"
            mchk = _extended.checksum
            mcrop = _extended.crop_count
            nfeat = len(_extended.features)

        else:  # both
            if not _hybrid:
                raise HTTPException(503, "Hybrid model unavailable")
            proba = _hybrid.predict_proba(input_dict)
            crops_list = _hybrid.unified_crops
            mtype = "hybrid-v6-rf"
            mchk = f"{_soil.checksum}+{_extended.checksum}"
            mcrop = _hybrid.crop_count
            nfeat = 10

    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Inference failed mode=%s", mode)
        raise HTTPException(500, f"Inference error: {e}")

    # 5. Confidence gating
    top_prob = float(np.max(proba))
    entropy = compute_entropy(proba)
    low_conf = top_prob < MIN_CONFIDENCE_THRESHOLD

    # 6. Build response
    top_n = data.top_n or 3
    top_idx = np.argsort(proba)[-top_n:][::-1]

    predictions = []
    for idx in top_idx:
        if mode == "both":
            cname = crops_list[idx]
        elif mode == "soil":
            cname = _soil.label_encoder.inverse_transform([idx])[0]
        else:
            cname = _extended.label_encoder.inverse_transform([idx])[0]

        cpct = round(float(proba[idx]) * 100, 2)
        predictions.append({
            "crop": cname,
            "confidence": cpct,
            "risk_level": risk_level(cpct),
            "nutrition": get_nutrition(cname),
        })

    latency = round((time.time() - start) * 1000, 1)

    resp: Dict[str, Any] = {
        "mode": mode,
        "predictions": predictions,
        "top_3": predictions[:3],
        "model_info": {
            "version": "6.0",
            "type": mtype,
            "crops": mcrop,
            "checksum": mchk,
            "features_used": nfeat,
        },
        "confidence_info": {
            "top_probability": round(top_prob * 100, 2),
            "entropy": round(entropy, 4),
            "low_confidence": low_conf,
        },
        "environment_info": {
            "season_used": get_season_name(season),
            "season_inferred": data.season is None,
            "soil_type": data.soil_type,
            "irrigation": data.irrigation,
            "moisture": data.moisture,
        },
        "latency_ms": latency,
    }

    # Deprecation notice for old mode names
    if deprecated_mode:
        resp["deprecation_notice"] = (
            f"Mode '{raw_mode}' is deprecated. Mapped to '{mode}'. "
            f"Use '{mode}' directly."
        )

    if ood_warnings:
        resp["ood_warnings"] = ood_warnings
        resp["warning"] = (
            f"Input(s) outside training distribution: "
            f"{', '.join(w['field'] for w in ood_warnings)}. "
            "Prediction may be less reliable."
        )
    if low_conf:
        w = resp.get("warning", "")
        resp["warning"] = (w + " Low confidence prediction. Conditions may be ambiguous.").strip()
    if entropy > ENTROPY_WARNING_THRESHOLD:
        w = resp.get("warning", "")
        resp["warning"] = (w + " High entropy — model uncertain.").strip()

    # 7. Full-vector logging
    logger.info(
        "PREDICT mode=%s crop=%s conf=%.1f%% entropy=%.3f ms=%.0f "
        "N=%.1f P=%.1f K=%.1f T=%.1f H=%.1f pH=%.1f R=%.1f "
        "soil=%d irrig=%d season=%d",
        mode, predictions[0]["crop"] if predictions else "-",
        top_prob * 100, entropy, latency,
        data.N, data.P, data.K, data.temperature, data.humidity,
        data.ph, data.rainfall,
        data.soil_type or 1, data.irrigation or 0, season,
    )

    return resp


# ═══════════════════════════════════════════════════════════════════════════
# INFO ENDPOINTS
# ═══════════════════════════════════════════════════════════════════════════

@app.get("/predict")
def predict_hint():
    return {
        "message": "Use POST with JSON body.",
        "version": "6.0",
        "modes": sorted(CANONICAL_MODES),
        "aliases": {"original": "soil", "synthetic": "extended"},
    }


@app.get("/")
def health():
    return {
        "status": "online",
        "version": "6.0",
        "architecture": "V6 soil-driven stacked ensemble",
        "models": {
            "soil": {
                "loaded": _soil is not None,
                "type": "stacked-ensemble-v6",
                "crops": _soil.crop_count if _soil else 0,
                "checksum": _soil.checksum if _soil else None,
            },
            "extended": {
                "loaded": _extended is not None,
                "type": "calibrated-rf",
                "crops": _extended.crop_count if _extended else 0,
                "checksum": _extended.checksum if _extended else None,
            },
            "both": {
                "loaded": _hybrid is not None,
                "type": "hybrid-v6-rf",
                "crops": _hybrid.crop_count if _hybrid else 0,
            },
        },
    }


@app.get("/crops")
def get_crops():
    out = {}
    if _soil:
        out["soil"] = sorted(_soil.crops)
    if _extended:
        out["extended"] = sorted(_extended.crops)
    if _hybrid:
        out["both"] = sorted(_hybrid.unified_crops)
    return out


@app.get("/limits")
def get_limits():
    """Feature validation ranges — single source of truth for all layers."""
    return FEATURE_RANGES
